-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "brand" SET NOT NULL,
ALTER COLUMN "brand" SET DATA TYPE TEXT,
ALTER COLUMN "description" SET NOT NULL,
ALTER COLUMN "description" SET DATA TYPE TEXT;
